- name: Include common vars and tasks
  block: 
  - include_vars :
      file: kubernetes.yaml
  - include_tasks: 'kube_tasks.yaml'

- name: Install docker
  shell: which docker || curl -sSL https://get.docker.com | sh &&  usermod -aG docker {{ ansible_user }}
  when: test is undefined

- name: Install needed packages
  apt:
    force_apt_get: yes
    name: conntrack
    state: present
  when: test is undefined

- name: Get kubelet, kubeproxy and kubectl 
  get_url:
    dest: "{{ binary_src }}"
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kube_tag.stdout }}/bin/linux/{{ hardware_architechture }}/{{ item }}
    mode: 0755
    remote_src: yes
  with_items: ["kubelet", "kube-proxy", "kubectl"] 
  when: test is undefined

# - name: download and extract kubelet files 
#   block:
#   - file: 
#       path: /opt/cni
#       state: directory
#   - unarchive: 
#       remote_src: yes 
#       creates: /opt/cni/bin
#       src: https://raw.githubusercontent.com/robertojrojas/kubernetes-the-hard-way-raspberry-pi/master/cni/cni.tar.gz
#       dest: /opt/cni/

- name: Generate config and services
  block: 
  - shell: echo "/home/$(logname)/.kube/"
    register: result
  - set_fact: config_path={{ result.stdout ~ 'config' }}
  - file: 
      path: "{{ result.stdout }}"
      state: directory
  - template:
      src: kubeconfig.j2
      dest: "{{ config_path }}"
  - template:
      src: "{{ item }}"
      dest: /etc/systemd/system/{{ item[:-3] | basename }}
    with_fileglob: templates/*.service.j2
    notify: Enables and start services
