---

- hosts: master
  become: yes
  gather_facts: no+
  tasks:
  - add_host:
      hostname: "{{ workers_prefix ~ (index + 1) }}"
      mac: "{{ item }}"
      groups: workers
    with_items: "{{ workers }}"
    loop_control:
      index_var: index
    when: add is defined
  roles: 
  - common-master 
  - kubernetes-master
  environment:
        ANSIBLE_HOST_KEY_CHECKING: False

- hosts: workers
  become: yes
  gather_facts: no 
  roles:
  - common-workers  
  - kubernetes-workers

...
