private_nic: enx0050b62623b8
public_nic: eth0

private_mask: 255.255.255.0
host_number: 15


# DNS 

# A=3, B=2, C=1
private_class: 1 
reverse_filename: "{{ (private_net.split('.') | reverse | list)[private_class:] | join('.') }}"
forwarded_dns: 141.64.3.55
domain_name: pi.lan