- name: Add workers to inventory
  add_host:
    hostname: "{{ workers_prefix ~ (index + 1) }}"
    mac: "{{ item }}"
    groups: workers
  with_items: "{{ workers }}"
  loop_control:
    index_var: index

- include_tasks: common_tasks.yaml

- name: Configure network manager to leave us alone 
  lineinfile: 
    dest: /etc/NetworkManager/NetworkManager.conf
    regexp: "^(unmanaged-devices).+?ethernet"
    line: '\1=*'
    backrefs: yes

- name: Install needed packages
  apt:
    force_apt_get: yes
    name: [ isc-dhcp-server, bind9, kmod, ifupdown2, curl ]
    state: present
  when: test != "true" or test is undefined

- name: Configure bind as a forwarding dns
  lineinfile: 
    dest: /etc/bind/named.conf.options
    insertafter: options {
    line: forwarders { {{ forwarded_dns }}; };
  notify: dns 

- name: Generate template 
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify: "{{ item.not | default('')}}" 
  with_items: 
  - { src: interfaces.j2, dest: /etc/network/interfaces, not: network }
  - { src: isc-dhcp-server.j2 , dest: /etc/default/isc-dhcp-server, not: dhcp  }
  - { src: dhcpd.conf.j2 , dest: /etc/dhcp/dhcpd.conf, not: dhcp }

- name: Add iptables modules
  modprobe:
    name: iptable_nat
    state: present
  with_items: "iptable_nat, iptables_filter, nf_conntrack_ipv4"

- name: Enable IP forwarding
  shell: echo "1" > /proc/sys/net/ipv4/ip_forward

- name: Iptables rules
  block: 
  - iptables:
      table: nat
      chain: POSTROUTING
      out_interface: "{{ public_nic }}"
      jump: MASQUERADE
  - iptables:
      chain: FORWARD
      in_interface: "{{ public_nic }}"
      out_interface: "{{ private_nic }}"
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT
  - iptables:
      chain: FORWARD
      in_interface: "{{ private_nic }}"
      jump: ACCEPT

- name: execute handlers
  meta: flush_handlers

- name: Wait for workers to get IP
  wait_for: 
    host: "{{ hostvars[item].ansible_host }}"
    port: 22
  register: result
  with_items: "{{ groups['workers'] }}"

# - name: Do dhclient on workers...
#   shell: sleep 15
