etcd_client_port: "2379"
etcd_peer_port: "2380"
etcd_addr: "{{ 'https://' ~ master_private ~ ':' ~ etcd_client_port }}"

services: ["etcd.service", "kube-apiserver.service", "kube-scheduler.service", "kube-controller-manager.service"]
