etcd_port: 2379
etcd_addr: "{{ 'https://' ~ master_private ~ ':' ~ etcd_port }}"

master_port: 6443
master_addr: "{{ 'https://' ~ master_private ~ ':' ~ master_port }}"
cluster_name: test

services: ["etcd.service", "kube-apiserver.service", "kube-scheduler.service", "kube-controller-manager.service"]

local_cert: "{{ playbook_dir ~ 'pki' }}"

remote_src: /etc/kubernetes/
remote_cert: "{{ remote_src ~ 'pki' }}"