---

- name: Include Kubernetes vars
  include_vars :
    file: kubernetes.yaml

- include_tasks: kube_common_tasks.yaml

- name: get api-server, scheduler, controller-manager
  get_url:
    dest: /usr/bin
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kube_tag.stdout }}/bin/linux/{{ hardware_architechture }}/{{ item }}
    mode: 0755
  with_items: 
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  when: test != "true" or test is undefined

- name: download and extract etcd files 
  unarchive: 
    remote_src: yes 
    creates: /usr/bin/etcd
    src: https://github.com/coreos/etcd/releases/download/v3.3.13/etcd-v3.3.13-linux-{{ hardware_architechture }}.tar.gz
    dest: /
    exclude: 
      - Documentation
      - README*
  register: result

- name: mv file from parent folder
  shell: mv /etcd*/* /usr/bin
  when: result.skipped is undefined

- name: Copy certificate to remote
  copy: 
    src: "{{ local_cert ~ '/' ~ item }}"
    dest: "{{ remote_cert }}"
  with_items:
    - "ca.pem"
    - "kubernetes-key.pem"
    - "kubernetes.pem"
  
- name: Copy auth file to remote 
  copy: 
    src: "auth.json"
    dest: "{{ remote_src }}"
   
- name: Generate services
  template: 
    src: "{{ item ~ '.j2' }}"
    dest: /etc/systemd/system/{{ item }}
  with_items: "{{ services }}"
  notify: Enables and start services

...
