- name: Include common vars and tasks
  block: 
  - include_vars :
      file: kubernetes.yaml
  - include_tasks: 'kube_tasks.yaml'

- name: get api-server, scheduler, controller-manager
  get_url:
    dest: "{{ binary_src }}"
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kube_tag.stdout }}/bin/linux/{{ hardware_architechture }}/{{ item }}
    mode: 0755
  with_items: 
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  when: test != "true" or test is undefined

- name: download and extract etcd files 
  unarchive: 
    remote_src: yes 
    creates: "{{ binary_src ~ 'etcd' }}"
    src: https://github.com/coreos/etcd/releases/download/v3.3.13/etcd-v3.3.13-linux-{{ hardware_architechture }}.tar.gz
    dest: /
    exclude: 
      - Documentation
      - README*
  register: result

- name: mv file from parent folder
  shell: mv /etcd*/* {{ binary_src }}
  when: result.skipped is undefined
  
- name: Copy auth file to remote 
  copy: 
    src: auth.json
    dest: "{{ remote_src }}"
  
- name: Generate services
  template: 
    src: "{{ item | basename }}"
    dest: /etc/systemd/system/{{ item[:-3] | basename }}
  with_fileglob: templates/*.service.j2
  notify: Enables and start services
